services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:${DB_PORT}", "--", "sh", "-c", "alembic upgrade head && flask run --host=0.0.0.0"]
    depends_on:
      - db
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      FLASK_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - my_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  test:
    build: .
    command: ["./wait-for-it.sh", "db:${DB_PORT}", "--", "sh", "-c", "alembic upgrade head && pytest"]
    environment:
      FLASK_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata: