"""Fix datetime usage in Qa model

Revision ID: 236df2ee173b
Revises: a8c5107828b8
Create Date: 2024-10-08 09:44:04.814726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236df2ee173b'
down_revision: Union[str, None] = 'a8c5107828b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
