"""Update timestamps to use timezone-aware datetime

Revision ID: d46ca5237eae
Revises: 4da6ee467006
Create Date: 2024-10-08 09:41:35.062616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46ca5237eae'
down_revision: Union[str, None] = '4da6ee467006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
